name: "postprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "537"
    data_type: TYPE_FP32
    dims: [ -1, 1, -1, -1 ]
   # reshape { shape: [ 1, 1, 1, 1 ] }
 
  },
  {
    name: "538"
    data_type: TYPE_FP32
    dims: [ -1, 2, -1, -1]
   
  },

  {
    name: "539"
    data_type: TYPE_FP32
    dims: [-1,  2, -1, -1]
  
  },
  {
    name: "540"
    data_type: TYPE_FP32
    dims: [-1, 10 , -1, -1]
    
  }
]

output [
  {
    name: "o537"
    data_type: TYPE_FP32
    dims: [ -1, 1, -1, -1 ]
  
    label_filename: "centerface_labels.txt"
  },
  {
    name: "o538"
    data_type: TYPE_FP32
    dims: [ -1, 2, -1, -1]
    label_filename: "centerface_labels.txt"
  },

  {
    name: "o539"
    data_type: TYPE_FP32
    dims: [-1,  2, -1, -1]
    label_filename: "centerface_labels.txt"
  },
  {
    name: "o540"
    data_type: TYPE_FP32
    dims: [-1, 10 , -1, -1]
    label_filename: "centerface_labels.txt"
  }
]

instance_group {
  count: 1
  gpus: 0
  kind: KIND_GPU
}
