name: "preprocess_face"
backend: "python"
max_batch_size: 256 
input [
{
    name: "INPUT_PREPROCESS_FACE"
    data_type: TYPE_UINT8
    dims: [ -1 ]
}
]
 
output [
{
    name: "OUTPUT_PREPROCESS_FACE"
    data_type: TYPE_FP32
    dims: [ 3, 112, 112 ]
}
]

instance_group [{ kind: KIND_CPU }]
