name: "preprocess"
backend: "python"
max_batch_size: 8
input [
  {
    name: "input"
    data_type: TYPE_FP32
#    format: FORMAT_NCHW
    dims: [3,-1, -1]
#    reshape { shape: [ 1, 3, 480, 640 ] }
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
#    format: FORMAT_NCHW
    dims: [3,112, 112]
#    reshape { shape: [ 1, 3, 480, 640 ] }
  }
]
