name: "preprocess"
backend: "python"
max_batch_size: 256 
input [
{
    name: "IMAGE_RAW"
    data_type: TYPE_UINT8
    dims: [ -1 ]
}
]
 
output [
{
    name: "IMAGE_PROCESS"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
}
]

instance_group [{ kind: KIND_CPU }]